ALTER TYPE "RoleCategory" ADD VALUE IF NOT EXISTS 'DATA';
ALTER TYPE "RoleCategory" ADD VALUE IF NOT EXISTS 'ML_AI';
ALTER TYPE "RoleCategory" ADD VALUE IF NOT EXISTS 'HARDWARE_EMBEDDED';
ALTER TYPE "RoleCategory" ADD VALUE IF NOT EXISTS 'ENGINEERING';
