export const COMPANY_BUCKETS = [
  "FAANG",
  "BIG_TECH",
  "QUANT",
  "TRADING",
  "HEDGE_FUND",
  "OTHER"
] as const;

export const SOURCE_TYPES = [
  "GREENHOUSE",
  "LEVER",
  "ASHBY",
  "WORKDAY",
  "CUSTOM_HTML",
  "CUSTOM_API",
  "BROWSER_AUTOMATION"
] as const;

export const ROLE_CATEGORIES = [
  "SWE",
  "QUANT_DEV",
  "QUANT_RESEARCH",
  "TRADING",
  "DATA_ML_AI",
  "SECURITY",
  "INFRA_SYSTEMS",
  "HARDWARE_FPGA_LOW_LATENCY",
  "PRODUCT_PM",
  "OTHER"
] as const;

export const REMOTE_TYPES = ["REMOTE", "HYBRID", "ONSITE", "UNKNOWN"] as const;

export const COMPENSATION_INTERVALS = [
  "HOUR",
  "YEAR",
  "MONTH",
  "WEEK",
  "DAY",
  "UNKNOWN"
] as const;

export const ALERT_CHANNELS = ["EMAIL", "DISCORD"] as const;

export const INTERNSHIP_SEASONS = ["SPRING", "SUMMER", "FALL", "WINTER"] as const;

export const LISTING_SORT_OPTIONS = [
  "newest",
  "postingDate",
  "discoveredDate",
  "company",
  "pay",
  "location"
] as const;

export const INTERNSHIP_INCLUDE_PATTERNS = [
  /\bintern(ship)?\b/i,
  /\bsummer analyst\b/i,
  /\bsummer associate\b/i,
  /\bsummer intern\b/i,
  /\boff[- ]cycle\b/i,
  /\bco[- ]?op\b/i,
  /\bstudent\b/i,
  /\buniversity\b/i,
  /\bcampus\b/i,
  /\bearly careers?\b/i,
  /\bundergraduate\b/i
] as const;

export const INTERNSHIP_EXCLUDE_PATTERNS = [
  /\bprincipal\b/i,
  /\bstaff\b/i,
  /\bsenior\b/i,
  /\blead\b/i,
  /\bmanager\b/i,
  /\bdirector\b/i,
  /\bexperienced\b/i,
  /\bfull[- ]time\b/i,
  /\bpermanent\b/i
] as const;

export const US_STATE_NAME_BY_CODE: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "District of Columbia"
};

export const COUNTRY_CODE_BY_NAME: Record<string, string> = {
  us: "US",
  usa: "US",
  "u s a": "US",
  "united states": "US",
  ca: "CA",
  can: "CA",
  canada: "CA",
  gb: "GB",
  gbr: "GB",
  uk: "GB",
  "united kingdom": "GB",
  england: "GB",
  ie: "IE",
  irl: "IE",
  ireland: "IE",
  de: "DE",
  deu: "DE",
  germany: "DE",
  nl: "NL",
  nld: "NL",
  netherlands: "NL",
  sg: "SG",
  sgp: "SG",
  singapore: "SG",
  fr: "FR",
  fra: "FR",
  france: "FR",
  ch: "CH",
  che: "CH",
  switzerland: "CH",
  au: "AU",
  aus: "AU",
  australia: "AU",
  jp: "JP",
  jpn: "JP",
  japan: "JP",
  hk: "HK",
  hkg: "HK",
  "hong kong sar": "HK",
  es: "ES",
  esp: "ES",
  spain: "ES",
  jo: "JO",
  jor: "JO",
  jordan: "JO",
  eg: "EG",
  egy: "EG",
  egypt: "EG",
  cn: "CN",
  chn: "CN",
  china: "CN",
  "people s republic of china": "CN",
  "peoples republic of china": "CN",
  ae: "AE",
  are: "AE",
  uae: "AE",
  "united arab emirates": "AE",
  il: "IL",
  isr: "IL",
  israel: "IL",
  tr: "TR",
  tur: "TR",
  turkey: "TR",
  turkiye: "TR",
  "t rkiye": "TR",
  "turkiye cumhuriyeti": "TR",
  bh: "BH",
  bhr: "BH",
  bahrain: "BH",
  tw: "TW",
  twn: "TW",
  taiwan: "TW",
  za: "ZA",
  zaf: "ZA",
  "south africa": "ZA",
  kr: "KR",
  kor: "KR",
  korea: "KR",
  "south korea": "KR",
  sa: "SA",
  sau: "SA",
  "saudi arabia": "SA",
  my: "MY",
  mys: "MY",
  malaysia: "MY",
  cl: "CL",
  chl: "CL",
  chile: "CL",
  co: "CO",
  col: "CO",
  colombia: "CO",
  cr: "CR",
  cri: "CR",
  "costa rica": "CR",
  it: "IT",
  ita: "IT",
  italy: "IT",
  in: "IN",
  ind: "IN",
  india: "IN",
  mx: "MX",
  mex: "MX",
  mexico: "MX",
  br: "BR",
  bra: "BR",
  brazil: "BR",
  pl: "PL",
  pol: "PL",
  poland: "PL",
  se: "SE",
  swe: "SE",
  sweden: "SE",
  lu: "LU",
  lux: "LU",
  luxembourg: "LU",
  at: "AT",
  aut: "AT",
  austria: "AT",
  pt: "PT",
  prt: "PT",
  portugal: "PT",
  cz: "CZ",
  cze: "CZ",
  czechia: "CZ",
  "czech republic": "CZ",
  ro: "RO",
  rou: "RO",
  romania: "RO",
  sk: "SK",
  svk: "SK",
  slovakia: "SK",
  be: "BE",
  bel: "BE",
  belgium: "BE",
  dk: "DK",
  dnk: "DK",
  denmark: "DK",
  fi: "FI",
  fin: "FI",
  finland: "FI",
  no: "NO",
  nor: "NO",
  norway: "NO",
  "hong kong": "HK"
};
