import { listingFilterSchema } from "@swe-quant/shared";
import { ListingFilterFields } from "../../components/listing-filter-fields";
import { SaveSearchSettingsForm } from "../../components/save-search-settings-form";
import { Button, Card, CardContent, Container, Input, PageHeader } from "@swe-quant/ui";
import { PortableDataManager } from "../../components/portable-data-manager";
import {
  saveDiscordSettingsAction,
  testDiscordDestinationAction,
  updateSettingsAction
} from "../../lib/actions";
import { getLocalProfile, isPlaceholderLocalEmail } from "../../lib/local-profile";
import { getDiscordSettings, getListingFilterMetadata } from "../../lib/queries";

export default async function SettingsPage() {
  const user = await getLocalProfile();
  const [discord, companies] = await Promise.all([
    getDiscordSettings(user.id),
    getListingFilterMetadata()
  ]);
  const notificationFilters = discord.destination?.filters ?? listingFilterSchema.parse({});
  const savedSearchFilters = listingFilterSchema.parse({});

  return (
    <Container className="space-y-8 py-10">
      <PageHeader
        title="Local settings and backups"
      />
      <Card className="max-w-xl rounded-xl shadow-none">
        <CardContent className="space-y-4">
          <form action={updateSettingsAction} className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">Notification email (optional)</label>
              <Input
                name="notificationEmail"
                type="email"
                defaultValue={isPlaceholderLocalEmail(user.email) ? "" : user.email}
                placeholder="you@example.com"
                maxLength={320}
                autoComplete="email"
              />
              <p className="text-xs text-slate-500">This is only an alert destination. It is not an account or sign-in.</p>
            </div>
            <label className="flex items-center gap-2 text-sm text-slate-700">
              <input type="checkbox" name="alertEmailsEnabled" defaultChecked={user.alertEmailsEnabled} />
              Email alerts enabled
            </label>
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">Digest timezone</label>
              <Input
                name="digestTimezone"
                defaultValue={user.digestTimezone}
                maxLength={100}
                autoComplete="off"
                required
              />
            </div>
            <Button type="submit">Save settings</Button>
          </form>
        </CardContent>
      </Card>
      <Card className="max-w-3xl rounded-xl shadow-none">
        <CardContent className="space-y-5">
          <div>
            <h2 className="font-display text-xl font-semibold text-ink">Discord notifications</h2>
            <p className="mt-1 text-sm text-slate-600">
              Connect a Discord server with a server webhook, then choose which early career roles
              should be announced. Messages are queued durably and delivered right after
              each ingestion cycle, with retries for temporary Discord outages.
            </p>
          </div>

          <div className="rounded-lg border border-brand-200 bg-brand-50 px-4 py-3 text-sm text-brand-900">
            Create a webhook in <span className="font-semibold">Server Settings → Integrations → Webhooks</span>.
            The webhook secret is stored locally and is never shown in this page or a backup export.
          </div>

          <form action={saveDiscordSettingsAction} className="space-y-5">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700" htmlFor="discordWebhookUrl">
                Discord server webhook
              </label>
              <Input
                id="discordWebhookUrl"
                name="discordWebhookUrl"
                type="password"
                placeholder={discord.destination ? "Saved webhook (leave blank to keep it)" : "https://discord.com/api/webhooks/..."}
                maxLength={2048}
                autoComplete="new-password"
              />
              <p className="text-xs text-slate-500">
                Only HTTPS webhooks generated by Discord are accepted. Anyone with this URL can post to the server.
              </p>
            </div>

            <label className="flex items-center gap-2 text-sm text-slate-700">
              <input
                type="checkbox"
                name="discordEnabled"
                defaultChecked={discord.destination?.enabled ?? true}
              />
              Send Discord notifications
            </label>

            <fieldset className="space-y-4">
              <legend className="text-sm font-medium text-slate-700">Notification filters</legend>
              <p className="text-sm text-slate-600">
                Use the same country, location, and position filters as the feed to choose which postings are sent to Discord.
                These settings are saved separately and do not change your feed filters.
              </p>
              <ListingFilterFields
                companies={discord.companies}
                filters={notificationFilters}
                multipleCompanies
                showSort={false}
                idPrefix="discord-filter"
              />
            </fieldset>

            {discord.destination ? (
              <label className="flex items-center gap-2 text-sm text-slate-500">
                <input type="checkbox" name="clearDiscordWebhook" />
                Remove the saved webhook and disable Discord
              </label>
            ) : null}

            <Button type="submit">Save Discord settings</Button>
          </form>

          {discord.destination ? (
            <div className="flex flex-col gap-3 border-t border-slate-200 px-1 py-4 text-sm sm:flex-row sm:items-center sm:justify-between">
              <div>
                <div className="font-semibold text-slate-800">
                  {discord.destination.enabled ? "Discord is enabled" : "Discord is paused"}
                </div>
                <div className="text-slate-500">
                  {notificationFilters.companySlugs.length ? `${notificationFilters.companySlugs.length} companies selected` : "All companies"} · Notification filters applied
                  {discord.destination.lastTestedAt ? ` · Last tested ${discord.destination.lastTestedAt.toLocaleString()}` : ""}
                </div>
                {discord.destination.lastTestStatus === false ? (
                  <div className="mt-1 text-red-700">Last connection test failed: {discord.destination.lastError ?? "Unknown Discord error"}</div>
                ) : discord.destination.lastTestStatus === true ? (
                  <div className="mt-1 text-emerald-700">Connection test succeeded.</div>
                ) : null}
              </div>
              <form action={testDiscordDestinationAction}>
                <Button type="submit" variant="secondary">Send test message</Button>
              </form>
            </div>
          ) : null}
        </CardContent>
      </Card>
      <Card className="max-w-3xl rounded-xl shadow-none">
        <CardContent className="space-y-5">
          <div>
            <h2 className="font-display text-xl font-semibold text-ink">Saved search alerts</h2>
            <p className="mt-1 text-sm text-slate-600">
              Save a reusable feed search here. The filters below are independent from your Discord notification filters.
            </p>
          </div>
          <SaveSearchSettingsForm companies={companies} filters={savedSearchFilters} />
        </CardContent>
      </Card>
      <Card className="max-w-3xl rounded-xl shadow-none">
        <CardContent className="space-y-4">
          <div>
            <h2 className="font-display text-xl font-semibold text-ink">Portable backup</h2>
            <p className="mt-1 text-sm text-slate-600">
              Export settings, saved searches, saved jobs, application progress, companies, source configuration,
              and Discord notification filters as versioned JSON. Discord webhook secrets, raw posting caches,
              and ingestion logs are intentionally excluded.
            </p>
          </div>
          <PortableDataManager />
        </CardContent>
      </Card>
    </Container>
  );
}
