import { Button, Card, CardContent, Container, Input, PageHeader } from "@faang-quant/ui";
import { PortableDataManager } from "../../components/portable-data-manager";
import {
  saveDiscordSettingsAction,
  testDiscordDestinationAction,
  updateSettingsAction
} from "../../lib/actions";
import { getLocalProfile, isPlaceholderLocalEmail } from "../../lib/local-profile";
import { getDiscordSettings } from "../../lib/queries";

export default async function SettingsPage() {
  const user = await getLocalProfile();
  const discord = await getDiscordSettings(user.id);
  const selectedCompanyIds = new Set(discord.destination?.selectedCompanyIds ?? []);

  return (
    <Container className="space-y-8 py-12">
      <PageHeader
        title="Local settings and backups"
      />
      <Card className="max-w-xl">
        <CardContent className="space-y-4">
          <form action={updateSettingsAction} className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">Notification email (optional)</label>
              <Input
                name="notificationEmail"
                type="email"
                defaultValue={isPlaceholderLocalEmail(user.email) ? "" : user.email}
                placeholder="you@example.com"
                maxLength={320}
                autoComplete="email"
              />
              <p className="text-xs text-slate-500">This is only an alert destination. It is not an account or sign-in.</p>
            </div>
            <label className="flex items-center gap-2 text-sm text-slate-700">
              <input type="checkbox" name="alertEmailsEnabled" defaultChecked={user.alertEmailsEnabled} />
              Email alerts enabled
            </label>
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">Digest timezone</label>
              <Input
                name="digestTimezone"
                defaultValue={user.digestTimezone}
                maxLength={100}
                autoComplete="off"
                required
              />
            </div>
            <Button type="submit">Save settings</Button>
          </form>
        </CardContent>
      </Card>
      <Card className="max-w-3xl">
        <CardContent className="space-y-5">
          <div>
            <h2 className="font-display text-xl font-semibold text-ink">Discord notifications</h2>
            <p className="mt-1 text-sm text-slate-600">
              Connect a Discord server with a server webhook, then choose which tracked companies
              should announce new internships. Messages are queued durably and delivered right after
              each ingestion cycle, with retries for temporary Discord outages.
            </p>
          </div>

          <div className="rounded-2xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm text-brand-900">
            Create a webhook in <span className="font-semibold">Server Settings → Integrations → Webhooks</span>.
            The webhook secret is stored locally and is never shown in this page or a backup export.
          </div>

          <form action={saveDiscordSettingsAction} className="space-y-5">
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700" htmlFor="discordWebhookUrl">
                Discord server webhook
              </label>
              <Input
                id="discordWebhookUrl"
                name="discordWebhookUrl"
                type="password"
                placeholder={discord.destination ? "Saved webhook (leave blank to keep it)" : "https://discord.com/api/webhooks/..."}
                maxLength={2048}
                autoComplete="new-password"
              />
              <p className="text-xs text-slate-500">
                Only HTTPS webhooks generated by Discord are accepted. Anyone with this URL can post to the server.
              </p>
            </div>

            <label className="flex items-center gap-2 text-sm text-slate-700">
              <input
                type="checkbox"
                name="discordEnabled"
                defaultChecked={discord.destination?.enabled ?? true}
              />
              Send Discord notifications
            </label>

            <fieldset className="space-y-3">
              <legend className="text-sm font-medium text-slate-700">Companies to announce</legend>
              <p className="text-xs text-slate-500">
                Choose the tracked companies to announce. New postings from unselected companies stay out of Discord.
              </p>
              <div className="grid max-h-80 gap-2 overflow-y-auto rounded-2xl border border-slate-200 bg-slate-50 p-3 sm:grid-cols-2">
                {discord.companies.map((company) => (
                  <label key={company.id} className="flex items-center gap-2 rounded-xl px-2 py-2 text-sm text-slate-700 transition-colors hover:bg-white">
                    <input
                      type="checkbox"
                      name="discordCompanyId"
                      value={company.id}
                      defaultChecked={discord.destination ? selectedCompanyIds.has(company.id) : true}
                    />
                    <span className="min-w-0 truncate">{company.name}</span>
                    <span className="ml-auto shrink-0 text-xs text-slate-400">{company.companyBucket.replaceAll("_", " ")}</span>
                  </label>
                ))}
              </div>
            </fieldset>

            {discord.destination ? (
              <label className="flex items-center gap-2 text-sm text-slate-500">
                <input type="checkbox" name="clearDiscordWebhook" />
                Remove the saved webhook and disable Discord
              </label>
            ) : null}

            <Button type="submit">Save Discord settings</Button>
          </form>

          {discord.destination ? (
            <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm sm:flex-row sm:items-center sm:justify-between">
              <div>
                <div className="font-semibold text-slate-800">
                  {discord.destination.enabled ? "Discord is enabled" : "Discord is paused"}
                </div>
                <div className="text-slate-500">
                  {discord.destination.selectedCompanyIds.length} compan{discord.destination.selectedCompanyIds.length === 1 ? "y" : "ies"} selected
                  {discord.destination.lastTestedAt ? ` · Last tested ${discord.destination.lastTestedAt.toLocaleString()}` : ""}
                </div>
                {discord.destination.lastTestStatus === false ? (
                  <div className="mt-1 text-red-700">Last connection test failed: {discord.destination.lastError ?? "Unknown Discord error"}</div>
                ) : discord.destination.lastTestStatus === true ? (
                  <div className="mt-1 text-emerald-700">Connection test succeeded.</div>
                ) : null}
              </div>
              <form action={testDiscordDestinationAction}>
                <Button type="submit" variant="secondary">Send test message</Button>
              </form>
            </div>
          ) : null}
        </CardContent>
      </Card>
      <Card className="max-w-3xl">
        <CardContent className="space-y-4">
          <div>
            <h2 className="font-display text-xl font-semibold text-ink">Portable backup</h2>
            <p className="mt-1 text-sm text-slate-600">
              Export settings, saved searches, saved jobs, application progress, companies, source configuration,
              and Discord company selections as versioned JSON. Discord webhook secrets, raw posting caches,
              and ingestion logs are intentionally excluded.
            </p>
          </div>
          <PortableDataManager />
        </CardContent>
      </Card>
    </Container>
  );
}
